server:
  port: 8888

spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/juanmacintas/ejercicioMircroserviciosConfigRepo
          searchPaths: autores,autorizacion,biblioteca,bibliotecavaadin,libros,categorias,editoriales,zuul,zipkin*

endpoints:
  beans:
    sensitive: false
  refresh:
    sensitive: false